---
# Apache 2 web server installation

- name: Install Apache
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - apache2
   - php5-gd
   - libgd2-xpm-dev
   - libapache2-mod-php5

- name: Activate Apache cgi on Ubuntu 14.04
  file: src=/etc/apache2/mods-available/cgi.load dest=/etc/apache2/mods-enabled/cgi.load state=link owner=root group=root

- name: HTTP service state
  service: name=apache2 state=started enabled=yes

- name: Sync Apache folder with Vagrant folder
  shell: rm -rf /var/www && ln -fs /vagrant /var/www

